# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Check formatting (gofmt)
      shell: bash
      run: |
        fmt_out=$(gofmt -s -l .)
        if [[ -n "$fmt_out" ]]; then
          echo "Unformatted files:" >&2
          echo "$fmt_out" >&2
          echo "Run: gofmt -s -w ." >&2
          exit 1
        fi

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./...
